### ISSUE TITLE
Is it normal that FID affected by the num_gen option?

### ISSUE THREAD

**Issue by glynpu** [atong01/conditional-flow-matching#111]
Thanks for this great work.  

I have reproduced the claimed FID 3.5 on cifar10. But the [default FID computation](https://github.com/atong01/conditional-flow-matching/blob/main/examples/images/cifar10/compute_fid.py#L28) is quite time consuming(about 40 minutes) since it requires generating 50,000 images.

When I reduce the num_gen option to 5,000 in compute_fid.py, the resulted FID increases a lot, e.g. increased from 5.12 to 9.75.

Is this normal? According [FID's definition](https://en.wikipedia.org/wiki/Fr%C3%A9chet_inception_distance#/),   FID shall not affected by the num_gen.

<img width="733" alt="image" src="https://github.com/atong01/conditional-flow-matching/assets/14951566/b37c4dda-efd2-4d6a-aa20-8f7605bf0f64">

**Comment by kilianFatras** [comment]
Yes, it is normal. The FID is defined as the squared 2-Wasserstein distance between two approximated Gaussians. We first embed generated and real data within the deepest Inception layer (to compare features rather than pixels) and then, we compute Gaussian statistics of the generated and real samples. The more samples we have to compute the Gaussian statistics, the better the approximation is.

The process takes indeed ~35 min on 1 A100. Increasing the batch size and the number of GPUs can reduce this time accordingly.
