### ISSUE TITLE
`sbcfm` cannot perform well

### ISSUE THREAD

**Issue by cantabile-kwok** [atong01/conditional-flow-matching#24]
Hi and thanks for releasing the code for the fascinating work! I am getting my hand on this repo and found that I cannot get satisfactory results using the provided configs for `sbcfm`, i.e.
``` 
python src/train.py trainer=cpu model=sbcfm`
```
The generated samples are just noise:
<img width="640" alt="image" src="https://github.com/atong01/conditional-flow-matching/assets/58417810/dd1be959-8b44-49e3-b81b-b7e2029aa5f3">

Meanwhile, it is able to generate good results using `otcfm` and `cfm` (for `cfm` it may be needed to increase the max_epoch and hidden dimensions).

Would you give some suggestions on how to make this work? Thank you!

**Comment by atong01** [comment]
Ooops! Sorry about this. This is a remnant of an experiment I was running with averaging over the batch. Specifically the bug is here:
https://github.com/atong01/conditional-flow-matching/blob/9e915a82beabfd25a28257e86e75b1543a3e55fb/src/models/cfm_module.py#L372-L374

should be like the CFM code here https://github.com/atong01/conditional-flow-matching/blob/9e915a82beabfd25a28257e86e75b1543a3e55fb/src/models/cfm_module.py#L169-L174

This means that you're actually only training on one point in the batch. Working on a fix now.

**Comment by atong01** [comment]
Please let me know if this works better for you, and thanks for catching this.

We have been working on an updated version of the code which should be out sometime next week.

**Comment by cantabile-kwok** [comment]
@atong01 Yes, it is much better now 👍👍
